import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowLeft, Camera, Check, ChevronRight, CircleHelp, Clock3, FileText, Flashlight, HeartPulse, History as HistoryIcon, Image as ImageIcon, Languages, LockKeyhole, Menu, Mic, MoreHorizontal, ScanLine, Search, Settings2, ShieldCheck, Sparkles, Stethoscope, SunMedium, Trash2, Upload, UserRound, X, Zap } from 'lucide-react';

type Page = 'home' | 'history' | 'profile' | 'onboarding' | 'scanner' | 'result' | 'report';
type Profile = { name: string; age: string; language: string; conditions: string[]; allergies: string };
type Scan = { id: string; kind: 'Food' | 'Report'; name: string; date: string; score?: number; status: string; image: string; detail: string };

const foodImages: Record<string, string> = {
  chips: 'https://images.unsplash.com/photo-1621939514649-280e2aa9f6e8?auto=format&fit=crop&w=900&q=85',
  noodles: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=85',
  biscuit: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=900&q=85',
  drink: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=900&q=85',
  chana: 'https://images.unsplash.com/photo-1599599810694-c7c7d5bd3f6e?auto=format&fit=crop&w=900&q=85',
  makhana: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=900&q=85',
  fruit: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=900&q=85',
};

const demoProducts = [
  { name: 'Lays Classic Salted', category: 'Salty snack', score: 34, status: 'Limit', image: foodImages.chips, sugar: 'Low', salt: 'High', fat: 'High', protein: 'Low', fibre: 'Low', why: 'High salt and fat, so it is better as an occasional snack.', forYou: 'With a blood pressure profile, smaller portions are a kinder choice.', detail: 'Potato, edible vegetable oil, salt, spices and flavouring.' },
  { name: 'Maggi 2-Minute Noodles', category: 'Instant meal', score: 28, status: 'Avoid', image: foodImages.noodles, sugar: 'Low', salt: 'High', fat: 'Medium', protein: 'Low', fibre: 'Low', why: 'High sodium with very little fibre or protein.', forYou: 'Add vegetables and choose it less often if you are watching salt.', detail: 'Wheat flour, palm oil, salt, seasoning, acidity regulators.' },
  { name: 'Oreo', category: 'Cream biscuit', score: 20, status: 'Avoid', image: foodImages.biscuit, sugar: 'High', salt: 'Medium', fat: 'Medium', protein: 'Low', fibre: 'Low', why: 'High added sugar with low fibre.', forYou: 'Not ideal for frequent eating with a blood sugar profile.', detail: 'Wheat flour, sugar, vegetable oil, cocoa, raising agents.' },
  { name: 'Coca-Cola', category: 'Sweetened drink', score: 16, status: 'Avoid', image: foodImages.drink, sugar: 'High', salt: 'Low', fat: 'Low', protein: 'Low', fibre: 'Low', why: 'A lot of added sugar in a drink that does not fill you up.', forYou: 'Water, lemon water, or whole fruit is a better everyday choice.', detail: 'Carbonated water, sugar, caramel colour, acidity regulator.' },
];

const swaps = [
  { name: 'Roasted chana', reason: 'More fibre and protein for a steady snack.', tag: 'Budget friendly', image: foodImages.chana },
  { name: 'Makhana', reason: 'Light, crunchy, and easy to roast at home.', tag: 'Under ₹30', image: foodImages.makhana },
  { name: 'Fruit with nuts', reason: 'Natural sweetness with a little staying power.', tag: 'Everyday pick', image: foodImages.fruit },
];

const seedHistory: Scan[] = [
  { id: '1', kind: 'Food', name: 'Lays Classic Salted', date: 'Today, 6:42 PM', score: 34, status: 'Limit', image: foodImages.chips, detail: 'High salt and fat' },
  { id: '2', kind: 'Report', name: 'Blood test report', date: 'Yesterday, 9:10 AM', status: 'Review', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80', detail: 'Blood sugar above range' },
  { id: '3', kind: 'Food', name: 'Coconut water', date: '18 Sep, 5:18 PM', score: 82, status: 'Good Choice', image: foodImages.drink, detail: 'Low added sugar' },
];

function Logo({ small = false }: { small?: boolean }) { return <div className={'brand ' + (small ? 'brand-small' : '')}><span className="brand-mark"><HeartPulse size={small ? 16 : 20} strokeWidth={2.7} /></span><span>NutriDoc</span></div>; }
function StatusPill({ status }: { status: string }) { return <span className={'status-pill ' + status.toLowerCase().replace(' ', '-')}>{status}</span>; }
function ScoreRing({ score }: { score: number }) { const radius = 50; const circumference = 2 * Math.PI * radius; return <div className="score-ring" style={{ '--progress': `${(score / 100) * circumference}px` } as React.CSSProperties}><svg viewBox="0 0 120 120"><circle className="ring-track" cx="60" cy="60" r={radius} /><circle className="ring-progress" cx="60" cy="60" r={radius} /></svg><div className="score-number"><strong>{score}</strong><span>/100</span></div></div>; }
function BottomNav({ page, go }: { page: Page; go: (p: Page) => void }) { return <nav className="bottom-nav glass"><button className={page === 'home' ? 'active' : ''} onClick={() => go('home')}><SunMedium size={19} /><span>Home</span></button><button className={page === 'history' ? 'active' : ''} onClick={() => go('history')}><HistoryIcon size={19} /><span>History</span></button><button className={page === 'profile' ? 'active' : ''} onClick={() => go('profile')}><UserRound size={19} /><span>Profile</span></button></nav>; }
function Header({ page, go, onBack }: { page: Page; go: (p: Page) => void; onBack?: () => void }) { return <header className="topbar glass"><div className="desktop-only">{onBack ? <button className="icon-button" onClick={onBack}><ArrowLeft size={19} /></button> : <Logo small />}</div><div className="mobile-only">{onBack ? <button className="icon-button" onClick={onBack}><ArrowLeft size={19} /></button> : <Logo small />}</div><div className="desktop-links"><button className={page === 'home' ? 'active' : ''} onClick={() => go('home')}>Home</button><button className={page === 'history' ? 'active' : ''} onClick={() => go('history')}>History</button><button className={page === 'profile' ? 'active' : ''} onClick={() => go('profile')}>Profile</button><button className="sign-in">Sign in</button></div><div className="topbar-right"><button className="icon-button"><CircleHelp size={19} /></button><button className="avatar">A</button></div></header>; }

export default function App() {
  const [page, setPage] = useState<Page>(() => localStorage.getItem('nutridoc-seen') ? 'home' : 'onboarding');
  const [profile, setProfile] = useState<Profile>(() => JSON.parse(localStorage.getItem('nutridoc-profile') || '{"name":"Aarav","age":"18–35","language":"English","conditions":["Diabetes / High Blood Sugar"],"allergies":"None added"}'));
  const [history, setHistory] = useState<Scan[]>(() => JSON.parse(localStorage.getItem('nutridoc-history') || JSON.stringify(seedHistory)));
  const [selectedProduct, setSelectedProduct] = useState(demoProducts[0]);
  const [scanStage, setScanStage] = useState<'front' | 'ingredients' | 'analysing'>('front');
  const [cameraOn, setCameraOn] = useState(false);
  const [filter, setFilter] = useState<'All' | 'Food' | 'Reports'>('All');
  const videoRef = useRef<HTMLVideoElement>(null);
  useEffect(() => { localStorage.setItem('nutridoc-history', JSON.stringify(history)); }, [history]);
  useEffect(() => { localStorage.setItem('nutridoc-profile', JSON.stringify(profile)); }, [profile]);
  useEffect(() => { if (page !== 'scanner') stopCamera(); }, [page]);
  const go = (next: Page) => setPage(next);
  const startCamera = async () => { setCameraOn(true); try { const stream = await navigator.mediaDevices?.getUserMedia({ video: { facingMode: 'environment' }, audio: false }); if (videoRef.current) videoRef.current.srcObject = stream; } catch { /* demo mode keeps the scanner usable */ } };
  const stopCamera = () => { const stream = videoRef.current?.srcObject as MediaStream | null; stream?.getTracks().forEach(t => t.stop()); if (videoRef.current) videoRef.current.srcObject = null; setCameraOn(false); };
  const beginFoodScan = () => { setScanStage('front'); setPage('scanner'); startCamera(); };
  const capture = () => { if (scanStage === 'front') { setScanStage('ingredients'); } else if (scanStage === 'ingredients') { stopCamera(); setScanStage('analysing'); window.setTimeout(() => setPage('result'), 1400); } };
  const demoScan = (p = demoProducts[Math.floor(Math.random() * demoProducts.length)]) => { setSelectedProduct(p); setPage('result'); const item: Scan = { id: Date.now().toString(), kind: 'Food', name: p.name, date: 'Just now', score: p.score, status: p.status, image: p.image, detail: p.why }; setHistory(h => [item, ...h.filter(x => x.name !== p.name)].slice(0, 12)); };
  const saveProfile = () => { localStorage.setItem('nutridoc-seen', '1'); setPage('home'); };
  if (page === 'onboarding') return <Onboarding profile={profile} setProfile={setProfile} save={saveProfile} />;
  if (page === 'scanner') return <Scanner stage={scanStage} videoRef={videoRef} cameraOn={cameraOn} capture={capture} demo={() => demoScan()} onBack={() => { stopCamera(); setPage('home'); }} />;
  return <div className="app-shell"><Header page={page} go={go} onBack={page === 'result' || page === 'report' ? () => go('home') : undefined} /><main className="page-content fade-up">{page === 'home' && <Home profile={profile} onFood={beginFoodScan} onReport={() => go('report')} onDemo={() => demoScan()} history={history} openHistory={() => go('history')} />}{page === 'result' && <Result product={selectedProduct} profile={profile} save={() => demoScan(selectedProduct)} />}{page === 'report' && <Report onDemo={() => { const item: Scan = { id: Date.now().toString(), kind: 'Report', name: 'Blood test report', date: 'Just now', status: 'Review', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80', detail: 'Blood sugar above range' }; setHistory(h => [item, ...h].slice(0, 12)); }} />}{page === 'history' && <History history={history} filter={filter} setFilter={setFilter} clear={() => { if (confirm('Clear all saved scans?')) setHistory([]); }} />}{page === 'profile' && <ProfilePage profile={profile} setProfile={setProfile} />}</main><BottomNav page={page} go={go} /></div>;
}

function Onboarding({ profile, setProfile, save }: { profile: Profile; setProfile: (p: Profile) => void; save: () => void }) { const [step, setStep] = useState(0); const ages = ['Under 18', '18–35', '36–50', '51–65', '65+']; const langs = ['English', 'हिन्दी', 'বাংলা']; const conditions = ['Diabetes / High Blood Sugar', 'High Blood Pressure', 'High Cholesterol / Heart Health', 'Food Allergies', 'None']; const toggle = (c: string) => setProfile({ ...profile, conditions: c === 'None' ? ['None'] : profile.conditions.includes(c) ? profile.conditions.filter(x => x !== c) : [...profile.conditions.filter(x => x !== 'None'), c] }); return <div className="onboarding"><div className="onboarding-top"><Logo /><span className="step-count">{step + 1} of 3</span></div><div className="onboarding-body"><div className="eyebrow">A little setup</div><h1>{step === 0 ? 'Make your choices feel personal.' : step === 1 ? 'How should NutriDoc speak to you?' : 'Anything we should keep in mind?'}</h1><p className="lead">{step === 0 ? 'You can change these anytime. We keep it simple.' : step === 1 ? 'Pick the language that feels easiest to read.' : 'This helps us highlight what matters to you.'}</p>{step === 0 && <div className="option-grid">{ages.map(x => <button key={x} className={profile.age === x ? 'choice selected' : 'choice'} onClick={() => setProfile({ ...profile, age: x })}>{x}{profile.age === x && <Check size={17} />}</button>)}</div>}{step === 1 && <div className="language-pills">{langs.map(x => <button key={x} className={profile.language === x ? 'language selected' : 'language'} onClick={() => setProfile({ ...profile, language: x })}>{x}</button>)}</div>}{step === 2 && <div className="condition-list">{conditions.map(x => <button key={x} className="condition" onClick={() => toggle(x)}><span className={'select-ring ' + (profile.conditions.includes(x) ? 'selected' : '')}>{profile.conditions.includes(x) && <Check size={14} />}</span><span>{x}</span></button>)}</div>}<div className="onboarding-actions"><button className="primary-button" onClick={() => step < 2 ? setStep(step + 1) : save()}>{step < 2 ? 'Continue' : 'Start with NutriDoc'}<ChevronRight size={18} /></button><button className="text-button" onClick={save}>Skip for now</button></div></div><div className="onboarding-glow" /></div> }

function Home({ profile, onFood, onReport, onDemo, history, openHistory }: { profile: Profile; onFood: () => void; onReport: () => void; onDemo: () => void; history: Scan[]; openHistory: () => void }) { return <><section className="hero"><div><p className="eyebrow">{new Date().getHours() > 17 ? 'Good evening' : 'Good day'}, {profile.name}</p><h1>What would you like<br /><em>to check today?</em></h1><p className="hero-copy">Small scans. Clearer choices.</p></div><div className="hero-orb"><Sparkles size={22} /></div></section><section className="action-grid"><button className="action-card food-action" onClick={onFood}><span className="action-icon"><ScanLine size={25} /></span><span><strong>Scan Food</strong><small>Check ingredients, sugar, salt, and healthier swaps.</small></span><ChevronRight className="action-arrow" /></button><button className="action-card report-action" onClick={onReport}><span className="action-icon"><FileText size={25} /></span><span><strong>Understand Prescription / Report</strong><small>Read health reports in simple language.</small></span><ChevronRight className="action-arrow" /></button></section><section className="demo-strip"><span><Zap size={15} /> Demo mode</span><button onClick={onDemo}>Try a sample food scan <ChevronRight size={15} /></button></section><section className="section-head"><div><p className="eyebrow">Your trail</p><h2>Recent scans</h2></div>{history.length > 0 && <button className="link-button" onClick={openHistory}>View all <ChevronRight size={15} /></button>}</section><section className="recent-list">{history.slice(0, 3).map(item => <div className="recent-item" key={item.id}><img src={item.image} /><div className="recent-info"><strong>{item.name}</strong><small>{item.date} · {item.detail}</small></div>{item.score ? <span className="mini-score">{item.score}</span> : <span className="mini-doc"><FileText size={17} /></span>}</div>)}{history.length === 0 && <div className="empty-state"><Clock3 size={20} /><span>No scans yet. Your saved insights will appear here.</span></div>}</section><Safety /></> }

function Scanner({ stage, videoRef, cameraOn, capture, demo, onBack }: { stage: 'front' | 'ingredients' | 'analysing'; videoRef: React.RefObject<HTMLVideoElement>; cameraOn: boolean; capture: () => void; demo: () => void; onBack: () => void }) { const analysing = stage === 'analysing'; return <div className="scanner-page"><div className="scanner-backdrop">{cameraOn && <video ref={videoRef} autoPlay playsInline muted />}</div><div className="scanner-scrim" /><div className="scanner-ui"><div className="scanner-top"><button className="scan-close" onClick={onBack}><X size={20} /></button><span className="scan-label">Food scan</span><button className="scan-close"><MoreHorizontal size={20} /></button></div>{analysing ? <div className="analysis-state"><div className="liquid-orb"><span /><span /><span /></div><p className="eyebrow">Working gently</p><h2>Recognising product</h2><p>Reading ingredients and nutrition next.</p><div className="analysis-steps"><span className="done">✓ Front captured</span><span className="done">✓ Ingredients captured</span><span className="current">◌ Analysing nutrition</span><span>○ Finding better swaps</span></div></div> : <><div className="scanner-copy"><p className="eyebrow">{stage === 'front' ? 'Step 1 of 2' : 'Step 2 of 2'}</p><h1>{stage === 'front' ? 'Point at the front of a food packet' : 'Turn the packet around.'}</h1><p>{stage === 'front' ? 'Keep the product inside the frame. We will capture it when it is steady.' : 'Make sure the ingredients and nutrition table are bright and readable.'}</p></div><div className={'scan-frame ' + (stage === 'ingredients' ? 'ingredients-frame' : '')}><div className="corner tl" /><div className="corner tr" /><div className="corner bl" /><div className="corner br" /><div className="scan-line" /></div><div className="scanner-controls"><button><Flashlight size={19} /><small>Flash</small></button><button><ImageIcon size={19} /><small>Gallery</small></button><button className="shutter" onClick={capture}><span /></button><button><ScanLine size={19} /><small>Barcode</small></button><button onClick={demo}><Zap size={19} /><small>Demo</small></button></div></>}</div></div> }

function Result({ product, profile, save }: { product: typeof demoProducts[number]; profile: Profile; save: () => void }) { const [saved, setSaved] = useState(false); return <><section className="result-hero"><div className="result-image-wrap"><img src={product.image} /><span className="image-badge"><Check size={14} /> Scanned</span></div><div className="result-title"><div><p className="eyebrow">{product.category}</p><h1>{product.name}</h1></div><StatusPill status={product.status} /></div></section><section className="score-panel glass"><ScoreRing score={product.score} /><div className="score-copy"><p className="eyebrow">Your food check</p><h2>Health Score</h2><p>{product.score < 40 ? 'An occasional choice, not an everyday one.' : 'A nice option for regular days.'}</p><span className="score-note"><ShieldCheck size={15} /> Personalised for {profile.conditions[0] || 'your profile'}</span></div></section><section className="nutrition-section"><div className="section-head"><div><p className="eyebrow">The quick read</p><h2>Nutrition snapshot</h2></div><button className="icon-button"><CircleHelp size={17} /></button></div><div className="nutrition-grid">{[['Sugar', product.sugar], ['Salt', product.salt], ['Fat', product.fat], ['Protein', product.protein], ['Fibre', product.fibre]].map(([name, value]) => <div className="nutrition-item" key={name}><div className="nutrition-top"><span>{name}</span><b className={String(value).toLowerCase()}>{value}</b></div><div className="nutrition-bar"><i className={String(value).toLowerCase()} style={{ width: value === 'High' ? '88%' : value === 'Medium' ? '58%' : '27%' }} /></div></div>)}</div></section><section className="why-panel"><div className="why-icon"><HeartPulse size={19} /></div><div><p className="eyebrow">Why it matters</p><h3>{product.why}</h3><p>For you: {product.forYou}</p></div></section><section className="swaps-section"><div className="section-head"><div><p className="eyebrow">A kinder next choice</p><h2>Better choices for you</h2></div><Sparkles size={19} className="section-sparkle" /></div><div className="swaps-row">{swaps.map(s => <div className="swap-card" key={s.name}><img src={s.image} /><span className="swap-tag">{s.tag}</span><strong>{s.name}</strong><small>{s.reason}</small></div>)}</div></section><button className={'save-button ' + (saved ? 'saved' : '')} onClick={() => { setSaved(true); save(); }}>{saved ? <><Check size={18} /> Saved to history</> : <><LockKeyhole size={17} /> Save this scan</>}</button><Safety /></> }

function Report({ onDemo }: { onDemo: () => void }) { const [mode, setMode] = useState<'report' | 'prescription'>('report'); return <><section className="report-intro"><div className="report-symbol"><FileText size={27} /></div><p className="eyebrow">Simple health reading</p><h1>Understand your<br /><em>{mode === 'report' ? 'report.' : 'prescription.'}</em></h1><p>Take a photo, upload an image, or choose a PDF. We will keep the language clear.</p></section><div className="segmented"><button className={mode === 'report' ? 'active' : ''} onClick={() => setMode('report')}>Medical report</button><button className={mode === 'prescription' ? 'active' : ''} onClick={() => setMode('prescription')}>Prescription</button></div><div className="upload-panel glass"><div className="upload-icon"><Upload size={22} /></div><h3>Drop a file here</h3><p>JPG, PNG, or PDF · up to 10 MB</p><div className="upload-actions"><button className="secondary-button"><Camera size={17} /> Take a photo</button><button className="primary-button" onClick={onDemo}><Upload size={17} /> Use demo report</button></div></div><section className="report-result"><div className="section-head"><div><p className="eyebrow">Demo reading</p><h2>Blood test report</h2></div><StatusPill status="Review" /></div><div className="report-row"><div><strong>Blood Sugar</strong><small>Result · 142 mg/dL</small></div><span className="report-high">Above range</span></div><p className="meaning"><b>Meaning:</b> Higher than the listed reference range.</p><p className="next-step"><Stethoscope size={17} /><span><b>Next step:</b> Discuss this report with a doctor.</span></p><div className="prescription-note"><Mic size={17} /><span>Handwriting confidence is shown when text is unclear. Never guess a medicine name or dose.</span></div></section><Safety /></> }

function History({ history, filter, setFilter, clear }: { history: Scan[]; filter: 'All' | 'Food' | 'Reports'; setFilter: (f: 'All' | 'Food' | 'Reports') => void; clear: () => void }) { const items = filter === 'All' ? history : history.filter(x => filter === 'Food' ? x.kind === 'Food' : x.kind === 'Report'); return <><section className="page-heading"><p className="eyebrow">Your trail</p><h1>Saved scans</h1><p>Clear answers, kept close when you need them.</p></section><div className="filter-row">{(['All', 'Food', 'Reports'] as const).map(x => <button key={x} className={filter === x ? 'active' : ''} onClick={() => setFilter(x)}>{x}</button>)}</div><section className="history-list">{items.map(item => <div className="history-card" key={item.id}><img src={item.image} /><div className="history-copy"><div><strong>{item.name}</strong><StatusPill status={item.status} /></div><small>{item.kind} · {item.date}</small><p>{item.detail}</p></div><ChevronRight size={18} /></div>)}{items.length === 0 && <div className="empty-state large"><Search size={22} /><span>No saved scans in this view.</span></div>}</section>{history.length > 0 && <button className="clear-button" onClick={clear}><Trash2 size={15} /> Clear history</button>}<Safety /></> }

function ProfilePage({ profile, setProfile }: { profile: Profile; setProfile: (p: Profile) => void }) { return <><section className="page-heading"><p className="eyebrow">Your NutriDoc</p><h1>Profile</h1><p>Keep your everyday health context up to date.</p></section><section className="profile-identity glass"><div className="profile-avatar">A</div><div><h3>{profile.name}</h3><p>Guest account · Local on this device</p></div><button className="icon-button"><Settings2 size={18} /></button></section><div className="settings-group"><p className="eyebrow">Personalisation</p><label>Preferred language<div className="setting-control"><Languages size={17} /><select value={profile.language} onChange={e => setProfile({ ...profile, language: e.target.value })}><option>English</option><option>हिन्दी</option><option>বাংলা</option></select></div></label><label>Age range<div className="setting-control"><UserRound size={17} /><select value={profile.age} onChange={e => setProfile({ ...profile, age: e.target.value })}>{['Under 18', '18–35', '36–50', '51–65', '65+'].map(x => <option key={x}>{x}</option>)}</select></div></label><label>Health conditions<div className="condition-summary">{profile.conditions.map(x => <span key={x}>{x}</span>)}</div></label></div><div className="privacy-note"><LockKeyhole size={17} /><span><b>Your privacy matters.</b><br />Your profile and history stay on this device unless you choose to connect an account.</span></div><button className="signout-button">Sign out</button></> }
function Safety() { return <p className="safety"><ShieldCheck size={14} /> NutriDoc provides general health awareness only. It does not diagnose illness or replace a doctor or pharmacist.</p>; }
